def mostrar_menu():
    print("🔥 Elegir Opcion 🔥")
    print("\n🔐 GESTOR DE CONTRASEÑAS")
    print("1. Generar contraseñas")
    print("2. Ver contraseñas")
    print("3. Salir")
    print("4. Añadir sitio")
    print("5. Eliminar contraseña")
    print("6. Buscar contraseña")
    print("DEBUG MENU CORRECTO")